//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class allanlerouge_oltree_campaign_manager_Entities : DbContext
    {
        public allanlerouge_oltree_campaign_manager_Entities()
            : base("name=allanlerouge_oltree_campaign_manager_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_base_element> t_base_element { get; set; }
        public virtual DbSet<t_campaign> t_campaign { get; set; }
        public virtual DbSet<t_campaign_day> t_campaign_day { get; set; }
        public virtual DbSet<t_campaign_day_interaction> t_campaign_day_interaction { get; set; }
        public virtual DbSet<t_campaign_session> t_campaign_session { get; set; }
        public virtual DbSet<t_community> t_community { get; set; }
        public virtual DbSet<t_community_theme> t_community_theme { get; set; }
        public virtual DbSet<t_faction> t_faction { get; set; }
        public virtual DbSet<t_hexagon> t_hexagon { get; set; }
        public virtual DbSet<t_monster> t_monster { get; set; }
        public virtual DbSet<t_npc> t_npc { get; set; }
        public virtual DbSet<t_place> t_place { get; set; }
        public virtual DbSet<t_rumor> t_rumor { get; set; }
    }
}
