//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;

    [Table("T_BASE_ELEMENT")]
    public partial class BaseElement
    {
        [Key]
        [Column("ID")]
        public long id { get; set; }

        [Column("ID_CAMPAIGN")]
        public long id_campaign { get; set; }

        [Column("DESCRIPTION")]
        public string description { get; set; }

        [Column("NOTES")]
        public string notes { get; set; }

        [Column("DESCRIPTION_MD")]
        public string description_md { get; set; }

        [Column("NOTES_MD")]
        public string notes_md { get; set; }

        [Column("TYPE")]
        public int type { get; set; }
    
        /*public virtual T_CAMPAIGN T_CAMPAIGN { get; set; }
        public virtual T_HEXAGON T_HEXAGON { get; set; }
        public virtual T_NPC T_NPC { get; set; }
        public virtual T_PLACE T_PLACE { get; set; }
        public virtual T_FACTION T_FACTION { get; set; }
        public virtual T_COMMUNITY_THEME T_COMMUNITY_THEME { get; set; }
        public virtual T_CAMPAIGN_SESSION T_CAMPAIGN_SESSION { get; set; }
        public virtual T_CAMPAIGN_DAY T_CAMPAIGN_DAY { get; set; }
        public virtual T_CAMPAIGN_DAY_INTERACTION T_CAMPAIGN_DAY_INTERACTION { get; set; }
        public virtual T_RUMOR T_RUMOR { get; set; }
        public virtual T_MONSTER T_MONSTER { get; set; }*/
    }
}
