//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_base_element
    {
        [Key]
        [Column("Name")]
        public long id { get; set; }

        public long id_campaign { get; set; }

        public string description { get; set; }

        public string notes { get; set; }

        public string description_md { get; set; }

        public string notes_md { get; set; }

        public int type { get; set; }
    
        public virtual t_campaign t_campaign { get; set; }
        public virtual t_hexagon t_hexagon { get; set; }
        public virtual t_npc t_npc { get; set; }
        public virtual t_place t_place { get; set; }
        public virtual t_faction t_faction { get; set; }
        public virtual t_community_theme t_community_theme { get; set; }
        public virtual t_campaign_session t_campaign_session { get; set; }
        public virtual t_campaign_day t_campaign_day { get; set; }
        public virtual t_campaign_day_interaction t_campaign_day_interaction { get; set; }
        public virtual t_rumor t_rumor { get; set; }
        public virtual t_monster t_monster { get; set; }
    }
}
