//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;
    
    [Table("T_CAMPAIGN_DAY")]
    public partial class T_CAMPAIGN_DAY : BaseElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CAMPAIGN_DAY()
        {
            this.T_CAMPAIGN_DAY_INTERACTION = new HashSet<T_CAMPAIGN_DAY_INTERACTION>();
        }


        [Column("USABLE_RESSOURCES_CAPACITY")]
        public long usable_ressources_capacity { get; set; }

        [Column("USABLE_RESSOURCES_CARRIED")]
        public long usable_ressources_carried { get; set; }

        [Column("IMMOBILISED_RESSOURCES_CARRIED")]
        public long immobilised_ressources_carried { get; set; }

        [Column("GOODS_CARRIED")]
        public string goods_carried { get; set; }

        [Column("WEATHER")]
        public string weather { get; set; }

        [Column("DAY")]
        public long day { get; set; }

        [Column("WEEK")]
        public long week { get; set; }

        [Column("MONTH")]
        public long month { get; set; }

        [Column("YEAR")]
        public int year { get; set; }

        [Column("RESSOURCES_EVOLUTION")]
        public string ressources_evolution { get; set; }

        [Column("TODO")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CAMPAIGN_DAY_INTERACTION> T_CAMPAIGN_DAY_INTERACTION { get; set; }
    }
}
