//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_campaign_session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_campaign_session()
        {
            this.t_campaign_day_interaction = new HashSet<t_campaign_day_interaction>();
        }
    
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public string players { get; set; }
    
        public virtual t_base_element t_base_element { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_campaign_day_interaction> t_campaign_day_interaction { get; set; }
    }
}
