//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;

    [Table("T_COMMUNITY")]
    public partial class T_COMMUNITY : T_PLACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_COMMUNITY()
        {
            this.T_COMMUNITY_THEME = new HashSet<T_COMMUNITY_THEME>();
        }


        [Column("RELATION_PATROL_LEVEL")]
        public long relation_patrol_level { get; set; }

        [Column("SIZE")]
        public int size { get; set; }

        [Column("PEOPLE_MAIN_TYPE")]
        public int people_main_type { get; set; }

        [Column("TYPE")]
        public string type { get; set; }

        [Column("ADDITIONAL_TYPE_DATA")]
        public string additional_type_data { get; set; }

        [Column("TODO")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_COMMUNITY_THEME> T_COMMUNITY_THEME { get; set; }
    }
}
