//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;

    [Table("T_COMMUNITY_THEME")]
    public partial class T_COMMUNITY_THEME : BaseElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_COMMUNITY_THEME()
        {
            this.T_FACTION = new HashSet<T_FACTION>();
        }

        [Column("NAME")]
        public string name { get; set; }

        [Column("BASE")]
        public string @base { get; set; }

        [Column("ID_COMMUNITY")]
        public virtual T_COMMUNITY T_COMMUNITY { get; set; }

        [Column("TODO")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FACTION> T_FACTION { get; set; }
    }
}
