//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_community
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_community()
        {
            this.t_community_theme = new HashSet<t_community_theme>();
        }
    
        public long id { get; set; }
        public long relation_patrol_level { get; set; }
        public int size { get; set; }
        public int people_main_type { get; set; }
        public string type { get; set; }
        public string additional_type_data { get; set; }
    
        public virtual t_place t_place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_community_theme> t_community_theme { get; set; }
    }
}
