//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_faction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_faction()
        {
            this.t_community_theme = new HashSet<t_community_theme>();
        }
    
        public long id { get; set; }
        public string @base { get; set; }
        public int objectif { get; set; }
        public int dynamique { get; set; }
        public string chronique { get; set; }
        public int motivation { get; set; }
    
        public virtual t_base_element t_base_element { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_community_theme> t_community_theme { get; set; }
    }
}
