//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;

    [Table("T_FACTION")]
    public partial class T_FACTION : BaseElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_FACTION()
        {
            this.T_COMMUNITY_THEME = new HashSet<T_COMMUNITY_THEME>();
        }

        [Column("BASE")]
        public string @base { get; set; }

        [Column("OBJECTIF")]
        public int objectif { get; set; }

        [Column("DYNAMIQUE")]
        public int dynamique { get; set; }

        [Column("CHRONIQUE")]
        public string chronique { get; set; }

        [Column("MOTIVATION")]
        public int motivation { get; set; }

        [Column("TODO")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_COMMUNITY_THEME> T_COMMUNITY_THEME { get; set; }
    }
}
