//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;

    [Table("T_HEXAGON")]
    public partial class T_HEXAGON : BaseElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_HEXAGON()
        {
            this.T_RUMOR = new HashSet<T_RUMOR>();
            this.T_MONSTER = new HashSet<T_MONSTER>();
            this.T_PLACE = new HashSet<T_PLACE>();
        }

        [Column("COLUMN")]
        public long column { get; set; }

        [Column("ROW")]
        public long row { get; set; }

        [Column("EXPLORATION_LEVEL")]
        public long exploration_level { get; set; }

        [Column("ID_LAND_TYPE")]
        public long id_land_type { get; set; }

        [Column("TODO")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RUMOR> T_RUMOR { get; set; }

        [Column("TODO")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_MONSTER> T_MONSTER { get; set; }

        [Column("TODO")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PLACE> T_PLACE { get; set; }
    }
}
