//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_monster
    {
        public long id { get; set; }
        public long id_hexagon { get; set; }
        public string name { get; set; }
    
        public virtual t_base_element t_base_element { get; set; }
        public virtual t_hexagon t_hexagon { get; set; }
    }
}
