//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;

    [Table("T_NPC")]
    public partial class T_NPC : BaseElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_NPC()
        {
            this.T_PLACE = new HashSet<T_PLACE>();
        }

        [Column("NAME")]
        public string name { get; set; }

        [Column("TODO")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PLACE> T_PLACE { get; set; }
    }
}
