//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OltreeCampaignManagerBdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_place
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_place()
        {
            this.t_hexagon = new HashSet<t_hexagon>();
            this.t_npc = new HashSet<t_npc>();
        }
    
        public long id { get; set; }
        public int type { get; set; }
    
        public virtual t_base_element t_base_element { get; set; }
        public virtual t_community t_community { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_hexagon> t_hexagon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_npc> t_npc { get; set; }
    }
}
